### ISSUE TITLE
Create expedition images

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#170]
Re: Diary expedition
Could not add expedition background image. Added expedition image but now cant delete it.

**Comment by sbearcsiro** [comment]
@RhiannonStephens is this for the New Project Wizard or the Project Settings page?

**Comment by RhiannonStephens** [comment]
@sbearcsiro both. I couldn't load the background image when i was creating the expedition and then went to settings to try and couldn't. In settings I wanted to delete the expedition image and there is no button.

**Comment by aruizca** [comment]
I am quite sure that was not possible before. Don't know if it was like that by design (eg: you can only update the image and therefore once you upload an image, there will always be one) or because they run out of time back then and left that feature out. Anyhow, it makes sense to add the feature...

**Comment by sbearcsiro** [comment]
IMHO it doesn't make sense to remove the expedition image (not the background) - it gets used in a bunch of places, so it seems like it should be mandatory?

**Comment by aruizca** [comment]
I guess that was the reason it was not there before, which makes sense too...

**Comment by RhiannonStephens** [comment]
@sbearcsiro @aruizca why is there not just 1 image? Cant that same image be the banner and then be resized smaller for the card or wherever else it needs to be?

**Comment by sbearcsiro** [comment]
@RhiannonStephens we could do it that way, but I think the two images have different constraints... (the following is all IMHO, I'm obviously not a designer) the expedition image would generally want to be cropped so as to show the image's subject in full, whereas the background image would, amongst other things, want a dark background so that the project page text is sufficiently contrasted and the image's subject you'll presumably want offset to the right so it's not right underneath the text.

**Comment by RhiannonStephens** [comment]
@sbearcsiro this is working

**Comment by sbearcsiro** [comment]
@RhiannonStephens thanks!
