### ISSUE TITLE
Unable to validate in new site

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#191]
can’t open or validate tasks, the timer is just going on and on

**Comment by sbearcsiro** [comment]
This was due to trying to index and calculate achievements for the user in the request while a large indexing job was going on.  To fix, speed up indexing and achievement calculations.  Make indexing and achievement calculation always run on background queue and notify of achievements via server sent events or similar instead of on page load.
