### ISSUE TITLE
Tag search only searches by 'label' which are only countries

### ISSUE THREAD

**Issue by AdamWoodsAM** [AtlasOfLivingAustralia/volunteer-portal#392]
Under the "Join a virtual expedition..." section, collection label and historical document lists link return zero results.
Collection labels applies the 'SPECIMEN' filter and historical document applies the 'FIELD NOTES' filter.

**Comment by cdausmus** [comment]
Looking into this, the project list search looks for tags in the labels table, which seems to be only country names (i.e. Australia, Bangladesh etc), whereas the project type is stored in a different table. If you view the project (expedition) list and click on the tag for a project (i.e. Specimen, Field notes or Camera Trap), it also brings back nothing.

The links on the home page can be fixed to use `q=Specimen` instead of `tag=Specimen` and this would bring back any project that references the term Specimen or Field Notes. The better fix would be to update the list search for tags to include the project type.

**Comment by sbearcsiro** [comment]
PR: LGTM
