### ISSUE TITLE
User Report

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#85]
The User Report button in the Admin tab is not working.

Note: This seems to be a timeout issue - the user report takes too long to start sending any data and the Apache -> Tomcat link times out.  To mitigate, we should modify the user report to write to an outputstream and flush the buffer occasionally.

**Comment by sbearcsiro** [comment]
@RhiannonStephens I've put a fix up for this on dev, which seems to work a tiny bit quicker and shouldn't time out now

**Comment by RhiannonStephens** [comment]
@sbearcsiro it brings back the correct columns of information but the information itself is not correct.
![image](https://cloud.githubusercontent.com/assets/10238220/7153334/8ba27028-e38d-11e4-8b3e-5152fde498da.png)
btw it works heaps quicker!!

**Comment by sbearcsiro** [comment]
@RhiannonStephens the discrepancy here is that the tasks completed and validated on the user list webpage is using a single value that is stored in the database, which is in theory the same as counting all the users tasks and validations.  But in the case of dev and Jim in particular, it has gotten a little out of sync.

I just grabbed a copy of the prod user report and a copy of the prod db to run the report on my laptop (which has the new code) so I can double check... and both CSVs are the same - so I'm pretty confident that the report is ok.

Having said that - we could use the pre calculated values from the db as well as / instead of the actual counts in the user report.  Would that be useful to you?

**Comment by RhiannonStephens** [comment]
@sbearcsiro sorry Simon, Im a bit confused. So the pre calculated values are the tasks transcribed and tasks validated by the volunteer? And the actual counts are the transcribed and validated added together? is that right? I would really like to have the counts for transcriptions, validations and total.

**Comment by sbearcsiro** [comment]
@RhiannonStephens sorry, this is pretty technical and obviously I didn't explain it clearly enough :(  So I'll try again...

In the database there is a field the contains the tasks transcribed and tasks validated counts, which is a stored value and has to be kept up to date by re-writing the value every time a user completes a transcription and validation.

The reason for storing this value rather than calculating it each time it's required isn't documented in the code or elsewhere (that I have seen).  Presumably it was for efficient display on various screens such as the user list, otherwise we'd have to count up each users transcriptions and validations each time the screen is displayed which can be time consuming.  Alternatively it might be so we can adjust a user's counts manually to correct a user's perceived injustices?

There is also a URL you can go to (it's not linked to from anywhere that I can find) which will reset each user's stored count value to their actual calculated count value.  The URL isn't linked to from anywhere, which means I suspect it was for a one time use... in dev it should be:

http://volunteer-dev.ala.org.au/admin/fixUserCounts
