### ISSUE TITLE
Picklist limit too small

### ISSUE THREAD

**Issue by johntann99** [AtlasOfLivingAustralia/volunteer-portal#93]
There appears to be a limit to the length of a picklist.
What works: uploading a list of 37,000 names
What doesn't work: uploading a list of 40,000 names

Symptoms. When uploading a long list of collectors, the 'Manage list' page disappeared, and was replaced by the 'Picklist List' page. The picklist did not get loaded.

Can you increase the picklist limit to say 100,000 please?

**Comment by sbearcsiro** [comment]
@johntann99 I've added a work around for large picklists which is deploying to the dev environment now, could you test it out and let me know how it works for you?

The issue is that the picklist is too large for our server's default HTTP POST size limits.  While we could adjust those limits, I personally prefer not to fiddle with those.  I also feel like working with a 40000+ sized picklist in the textbox on the web page is less than ideal - so I've added the ability to skip the textbox and just upload a CSV file for a picklist + institution combo.  Additionally, the upload button will now disable if the picklist is too large for the server to handle.

The "Upload a file" button can be found in the same place as the upload button on the bulk manage picklists admin page.

**Comment by johntann99** [comment]
Good one Simon,
That worked well for me.
It makes a lot more sense the way you've done it. For the future,  I can see some of the picklists that I am starting to work with will need to cope with 70,000 odd entries. This will be a better way to work with them.

I am happy for you to move this to production.
